services:
  client:
    ports:
      - 4200:4200
    command: "ng serve --host 0.0.0.0 --poll=2000 --port 4200 --disable-host-check"
    build:
      context: .
      dockerfile: Dockerfile    
    volumes:
      - ./:/app
      - /app/node_modules
    # networks:
    #   - front-network


# networks:
#   front-network:
#     driver: bridge

# Si un proceso dentro del contenedor necesita comunicarse, con otro contenedor, es necesario que estén en la misma red
# para este caso particular, no es necesario para garantizar la comunicación, ya que una vez llega al navegador
# el navegador si tiene acceso a la dirección del contenedor del backend
    # name: posts_app-network
    # external: true