version: '3.8'

services:
  angular:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
    networks:
      - prod-network

networks:
  prod-network:
    name: posts_prod-app-network
    external: true
